#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(main|bugfix\/([a-zA-Z0-9_-]+|[0-9]+(\/[a-zA-Z0-9_-]+)*)|hotfix\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+|dependencies\/[a-zA-Z0-9_-]+|feature\/[a-zA-Z0-9_-]+|tests\/([a-zA-Z0-9]+|[0-9]+(\/[a-zA-Z0-9_-]+)*)|release\/[0-9]+\.[0-9]+\.[0-9]+(-(beta|rc)[0-9]*)?)$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi
echo "check"
exit 0